### ISSUE TITLE
[App] Mint hypercert

### ISSUE THREAD

**Issue by Jipperism** [protocol/hypercerts-pilot#6]

**Comment by Jipperism** [comment]
@bitbeckers @moconnell

Spent most time today implementing the mint hypercertificate form, including ipfs uploads. It's nearly complete, just some loose ends we should probably discuss:
- Do we want to store cid's for the uploaded artifacts, or full ipfs links? I'm currently storing the image with some metadata ([see an example here](https://ipfs.io/ipfs/bafyreiggdfex2g4uba4kkw5hzf7ny2o74ljekfowabdw4e6xcazk2uhzda/metadata.json)). The json metadata is being stored as a blob ([see example here](https://ipfs.io/ipfs/bafkreiafs7vsdrlfbsrl6uxpqopgyzyjbznazfw5eq6i67tma57jmlncku)). Uploading as a blob only returns the cid, while storing the image with metadata returns a proper ipfs:// protocol link, including .json extension. I think it's trivial to construct the link from the cid but we should probably standardize and use the same in both places. Let me know if there is a preference for either.
- We should probably update the docs to show which fields are *required* and which are not, so I can add some validation to the frontend form.

**Comment by moconnell** [comment]
> - Do we want to store cid's for the uploaded artifacts, or full ipfs links? I'm currently storing the image with some metadata ([see an example here](https://ipfs.io/ipfs/bafyreiggdfex2g4uba4kkw5hzf7ny2o74ljekfowabdw4e6xcazk2uhzda/metadata.json)). The json metadata is being stored as a blob ([see example here](https://ipfs.io/ipfs/bafkreiafs7vsdrlfbsrl6uxpqopgyzyjbznazfw5eq6i67tma57jmlncku)). Uploading as a blob only returns the cid, while storing the image with metadata returns a proper ipfs:// protocol link, including .json extension. I think it's trivial to construct the link from the cid but we should probably standardize and use the same in both places. Let me know if there is a preference for either.

The assumption is that we are storing the full URI on our side.

> - We should probably update the docs to show which fields are required and which are not, so I can add some validation to the frontend form.

Yup.
